# Generated by Django 4.1.4 on 2022-12-07 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airfields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airfieldName', models.CharField(db_column='afdname', max_length=255)),
                ('groupId', models.CharField(db_column='group_id', max_length=255)),
                ('groupName', models.CharField(db_column='grname', max_length=255)),
                ('equipment', models.CharField(db_column='equipment', max_length=255)),
                ('groupLink', models.CharField(db_column='grlink', max_length=255)),
                ('airforceName', models.CharField(db_column='afname', max_length=255)),
                ('headQ', models.CharField(db_column='headq', max_length=255)),
                ('commander', models.CharField(db_column='commander', max_length=255)),
                ('airforceLink', models.CharField(db_column='wlink', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Airfields',
                'db_table': 'airfieldsag',
                'managed': False,
            },
        ),
    ]
