# Generated by Django 4.1.4 on 2022-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombSites',
            fields=[
                ('Id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('opDate', models.DateField(db_column='opdate')),
                ('groupId', models.CharField(db_column='group_id', max_length=255)),
                ('opOrder', models.CharField(db_column='oporder', max_length=255)),
                ('place', models.CharField(db_column='place', max_length=255)),
                ('target', models.CharField(db_column='target', max_length=255)),
                ('targetType', models.CharField(db_column='targettype', max_length=255)),
                ('opReport', models.CharField(db_column='opreport', max_length=255)),
                ('opPhoto', models.CharField(db_column='opphoto', max_length=255)),
                ('targetPhoto', models.CharField(db_column='targetphoto', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bomsites',
                'db_table': 'bombsites',
                'managed': False,
            },
        ),
    ]
